# -*- coding: utf-8 -*-
"""q4_DIP3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cbuPWnWkmY_k26LpwLieSndyjhLP1vcQ
"""

import cv2 as cv
import numpy as np

A = cv.imread('t-shirt.png')
A= cv.cvtColor(A, cv.COLOR_BGR2RGB)
print("t_shirt",A.shape)

A_ch1=A[:,:,0]
A_ch2=A[:,:,1]
A_ch3=A[:,:,2]
# plt.imshow(A)
# plt.figure()
# plt.show()
a_file = open("test.txt", "w")
for row in A:
    np.savetxt(a_file, row)

a_file.close()

import glob
import numpy as np
# for i in range(1,51):
# fullstring = ""
sub1 = "001"
sub2 = "002"
sub3 = "003"
sub4 = "004"
sub5 = "005"
sub6 = "006"
sub7 = "007"
sub8 = "008"
sub9 = "009"
sub10 = "010"
sub11 = "011"
sub12 = "012"
sub13 = "013"
sub14 = "014"
sub15 = "015"
sub16 = "016"
sub17 = "017"
sub18 = "018"
sub19 = "019"
sub20 = "020"
sub21 = "021"
sub22 = "022"
sub23 = "023"
sub24 = "024"
sub25 = "025"
sub26 = "026"
sub27 = "027"
sub28 = "028"
sub29 = "029"
sub30 = "030"
sub31 = "031"
sub32 = "032"
sub33 = "033"
sub34 = "034"
sub35 = "035"
sub36 = "036"
sub37 = "037"
sub38 = "038"
sub39 = "039"
sub40 = "040"
sub41 = "041"
sub42 = "042"
sub43 = "043"
sub44 = "044"
sub45 = "045"
sub46 = "046"
sub47 = "047"
sub48 = "048"
sub49 = "049"
sub50 = "050"
# sub15 = "050"
list1=[]
list2=[]
list3=[]
list4=[]
list5=[]
list6=[]
list7=[]
list8=[]
list9=[]
list10=[]
list11=[]
list11=[]
list12=[]
list13=[]
list14=[]
list15=[]
list16=[]
list17=[]
list18=[]
list19=[]
list20=[]
list21=[]
list22=[]
list23=[]
list24=[]
list25=[]
list26=[]
list27=[]
list28=[]
list29=[]
list30=[]
list31=[]
list32=[]
list33=[]
list34=[]
list35=[]
list36=[]
list37=[]
list38=[]
list39=[]
list40=[]
list41=[]
list42=[]
list43=[]
list44=[]
list45=[]
list46=[]
list47=[]
list48=[]
list49=[]
list50=[]
list_of_names=glob.glob("/content/drive/MyDrive/test2/M*0[1-9].bmp",recursive=True)
list_of_names2=glob.glob("/content/drive/MyDrive/test2/M*1[0-3].bmp",recursive=True)
for i in range(len(list_of_names2)):
  list_of_names.append(list_of_names2[i])
print(len(list_of_names))
for i in range(650):
  if sub1 in list_of_names[i]:
    # print ("Found!")
    list1.append(list_of_names[i])
  if sub2 in list_of_names[i]:
    # print ("Found!")
    list2.append(list_of_names[i])
  if sub3 in list_of_names[i]:
    # print ("Found!")
    list3.append(list_of_names[i])
  if sub4 in list_of_names[i]:
    # print ("Found!")
    list4.append(list_of_names[i])
  if sub5 in list_of_names[i]:
    # print ("Found!")
    list5.append(list_of_names[i])
  if sub6 in list_of_names[i]:
    # print ("Found!")
    list6.append(list_of_names[i])
  if sub7 in list_of_names[i]:
    # print ("Found!")
    list7.append(list_of_names[i])
  if sub8 in list_of_names[i]:
    # print ("Found!")
    list8.append(list_of_names[i])
  if sub9 in list_of_names[i]:
    # print ("Found!")
    list9.append(list_of_names[i])
  if sub10 in list_of_names[i]:
    # print ("Found!")
    list10.append(list_of_names[i])
  if sub11 in list_of_names[i]:
    # print ("Found!")
    list11.append(list_of_names[i])
  if sub12 in list_of_names[i]:
    # print ("Found!")
    list12.append(list_of_names[i])
  if sub13 in list_of_names[i]:
    # print ("Found!")
    list13.append(list_of_names[i])
  if sub14 in list_of_names[i]:
    # print ("Found!")
    list14.append(list_of_names[i])
  if sub15 in list_of_names[i]:
    # print ("Found!")
    list15.append(list_of_names[i])
  if sub16 in list_of_names[i]:
    # print ("Found!")
    list16.append(list_of_names[i])
  if sub17 in list_of_names[i]:
    # print ("Found!")
    list17.append(list_of_names[i])
  if sub18 in list_of_names[i]:
    # print ("Found!")
    list18.append(list_of_names[i])
  if sub19 in list_of_names[i]:
    # print ("Found!")
    list19.append(list_of_names[i])
  if sub20 in list_of_names[i]:
    # print ("Found!")
    list20.append(list_of_names[i])
  if sub21 in list_of_names[i]:
    # print ("Found!")
    list21.append(list_of_names[i])
  if sub22 in list_of_names[i]:
    # print ("Found!")
    list22.append(list_of_names[i])
  if sub23 in list_of_names[i]:
    # print ("Found!")
    list23.append(list_of_names[i])
  if sub24 in list_of_names[i]:
    # print ("Found!")
    list24.append(list_of_names[i])
  if sub25 in list_of_names[i]:
    # print ("Found!")
    list25.append(list_of_names[i])
  if sub26 in list_of_names[i]:
    # print ("Found!")
    list26.append(list_of_names[i])
  if sub27 in list_of_names[i]:
    # print ("Found!")
    list27.append(list_of_names[i])
  if sub28 in list_of_names[i]:
    # print ("Found!")
    list28.append(list_of_names[i])
  if sub29 in list_of_names[i]:
    # print ("Found!")
    list29.append(list_of_names[i])
  if sub30 in list_of_names[i]:
    # print ("Found!")
    list30.append(list_of_names[i])
  if sub31 in list_of_names[i]:
    # print ("Found!")
    list31.append(list_of_names[i])
  if sub32 in list_of_names[i]:
    # print ("Found!")
    list32.append(list_of_names[i])
  if sub33 in list_of_names[i]:
    # print ("Found!")
    list33.append(list_of_names[i])
  if sub34 in list_of_names[i]:
    # print ("Found!")
    list34.append(list_of_names[i])
  if sub35 in list_of_names[i]:
    # print ("Found!")
    list35.append(list_of_names[i])
  if sub36 in list_of_names[i]:
    # print ("Found!")
    list36.append(list_of_names[i])
  if sub37 in list_of_names[i]:
    # print ("Found!")
    list37.append(list_of_names[i])
  if sub38 in list_of_names[i]:
    # print ("Found!")
    list38.append(list_of_names[i])
  if sub39 in list_of_names[i]:
    # print ("Found!")
    list39.append(list_of_names[i])
  if sub40 in list_of_names[i]:
    # print ("Found!")
    list40.append(list_of_names[i])
  if sub41 in list_of_names[i]:
    # prnt ("Found!")
    list41.append(list_of_names[i])
  if sub42 in list_of_names[i]:
    # print ("Found!")
    list42.append(list_of_names[i])
  if sub43 in list_of_names[i]:
    # print ("Found!")
    list43.append(list_of_names[i])
  if sub44 in list_of_names[i]:
    # print ("Found!")
    list44.append(list_of_names[i])
  if sub45 in list_of_names[i]:
    # print ("Found!")
    list45.append(list_of_names[i])
  if sub46 in list_of_names[i]:
    # print ("Found!")
    list46.append(list_of_names[i])
  if sub47 in list_of_names[i]:
    # print ("Found!")
    list47.append(list_of_names[i])
  if sub48 in list_of_names[i]:
    # print ("Found!")
    list48.append(list_of_names[i])
  if sub49 in list_of_names[i]:
    # print ("Found!")
    list49.append(list_of_names[i])
  if sub50 in list_of_names[i]:
    # print ("Found!")
    list50.append(list_of_names[i])

print(len(list1))
a1=np.asarray(list1)
a2=np.asarray(list2)
a3=np.asarray(list3)
a4=np.asarray(list4)
a5=np.asarray(list5)
a6=np.asarray(list6)
a7=np.asarray(list7)
a8=np.asarray(list8)
a9=np.asarray(list9)
a10=np.asarray(list10)
a11=np.asarray(list11)
a12=np.asarray(list12)
a13=np.asarray(list13)
a14=np.asarray(list14)
a15=np.asarray(list15)
a16=np.asarray(list16)
a17=np.asarray(list17)
a18=np.asarray(list18)
a19=np.asarray(list19)
a20=np.asarray(list20)
a21=np.asarray(list21)
a22=np.asarray(list22)
a23=np.asarray(list23)
a24=np.asarray(list24)
a25=np.asarray(list25)
a26=np.asarray(list26)
a27=np.asarray(list27)
a28=np.asarray(list28)
a29=np.asarray(list29)
a30=np.asarray(list30)
a31=np.asarray(list31)
a32=np.asarray(list32)
a33=np.asarray(list33)
a34=np.asarray(list34)
a35=np.asarray(list35)
a36=np.asarray(list36)
a37=np.asarray(list37)
a38=np.asarray(list38)
a39=np.asarray(list39)
a40=np.asarray(list40)
a41=np.asarray(list41)
a42=np.asarray(list42)
a43=np.asarray(list43)
a44=np.asarray(list44)
a45=np.asarray(list45)
a46=np.asarray(list46)
a47=np.asarray(list47)
a48=np.asarray(list48)
a49=np.asarray(list49)
a50=np.asarray(list50)
a1 = np.reshape(a1,(1, a1.size))
a2 = np.reshape(a2,(1, a2.size))
a3 = np.reshape(a3,(1, a3.size))
a4 = np.reshape(a4,(1, a4.size))
a5 = np.reshape(a5,(1, a5.size))
a6 = np.reshape(a6,(1, a6.size))
a7 = np.reshape(a7,(1, a7.size))
a8 = np.reshape(a8,(1, a8.size))
a9 = np.reshape(a9,(1, a9.size))
a10 = np.reshape(a10,(1, a10.size))
a11 = np.reshape(a11,(1, a11.size))
a12 = np.reshape(a12,(1, a12.size))
a13 = np.reshape(a13,(1, a13.size))
a14 = np.reshape(a14,(1, a14.size))
a15 = np.reshape(a15,(1, a15.size))
a16 = np.reshape(a16,(1, a16.size))
a17 = np.reshape(a17,(1, a17.size))
a18 = np.reshape(a18,(1, a18.size))
a19 = np.reshape(a19,(1, a19.size))
a20 = np.reshape(a20,(1, a20.size))
a21 = np.reshape(a21,(1, a21.size))
a22 = np.reshape(a22,(1, a22.size))
a23 = np.reshape(a23,(1, a23.size))
a24 = np.reshape(a24,(1, a24.size))
a25 = np.reshape(a25,(1, a25.size))
a26 = np.reshape(a26,(1, a26.size))
a27 = np.reshape(a27,(1, a27.size))
a28 = np.reshape(a28,(1, a28.size))
a29 = np.reshape(a29,(1, a29.size))
a30 = np.reshape(a30,(1, a30.size))
a31 = np.reshape(a31,(1, a31.size))
a32 = np.reshape(a32,(1, a32.size))
a33 = np.reshape(a33,(1, a33.size))
a34 = np.reshape(a34,(1, a34.size))
a35 = np.reshape(a35,(1, a35.size))
a36 = np.reshape(a36,(1, a36.size))
a37 = np.reshape(a37,(1, a37.size))
a38 = np.reshape(a38,(1, a38.size))
a39 = np.reshape(a39,(1, a39.size))
a40 = np.reshape(a40,(1, a40.size))
a41 = np.reshape(a41,(1, a41.size))
a42 = np.reshape(a42,(1, a42.size))
a43 = np.reshape(a43,(1, a43.size))
a44 = np.reshape(a44,(1, a44.size))
a45 = np.reshape(a45,(1, a45.size))
a46 = np.reshape(a46,(1, a46.size))
a47 = np.reshape(a47,(1, a47.size))
a48 = np.reshape(a48,(1, a48.size))
a49 = np.reshape(a49,(1, a49.size))
a50 = np.reshape(a50,(1, a50.size))
print(a50.shape)
array1=np.concatenate((a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50))
print(array1.shape)

import glob
# for i in range(1,51):
# fullstring = ""
sub1 = "001"
sub2 = "002"
sub3 = "003"
sub4 = "004"
sub5 = "005"
sub6 = "006"
sub7 = "007"
sub8 = "008"
sub9 = "009"
sub10 = "010"
sub11 = "011"
sub12 = "012"
sub13 = "013"
sub14 = "014"
sub15 = "015"
sub16 = "016"
sub17 = "017"
sub18 = "018"
sub19 = "019"
sub20 = "020"
sub21 = "021"
sub22 = "022"
sub23 = "023"
sub24 = "024"
sub25 = "025"
sub26 = "026"
sub27 = "027"
sub28 = "028"
sub29 = "029"
sub30 = "030"
sub31 = "031"
sub32 = "032"
sub33 = "033"
sub34 = "034"
sub35 = "035"
sub36 = "036"
sub37 = "037"
sub38 = "038"
sub39 = "039"
sub40 = "040"
sub41 = "041"
sub42 = "042"
sub43 = "043"
sub44 = "044"
sub45 = "045"
sub46 = "046"
sub47 = "047"
sub48 = "048"
sub49 = "049"
sub50 = "050"
# sub15 = "050"
list1=[]
list2=[]
list3=[]
list4=[]
list5=[]
list6=[]
list7=[]
list8=[]
list9=[]
list10=[]
list11=[]
list11=[]
list12=[]
list13=[]
list14=[]
list15=[]
list16=[]
list17=[]
list18=[]
list19=[]
list20=[]
list21=[]
list22=[]
list23=[]
list24=[]
list25=[]
list26=[]
list27=[]
list28=[]
list29=[]
list30=[]
list31=[]
list32=[]
list33=[]
list34=[]
list35=[]
list36=[]
list37=[]
list38=[]
list39=[]
list40=[]
list41=[]
list42=[]
list43=[]
list44=[]
list45=[]
list46=[]
list47=[]
list48=[]
list49=[]
list50=[]
list_of_names=glob.glob("/content/drive/MyDrive/test2/W*0[1-9].bmp",recursive=True)
list_of_names2=glob.glob("/content/drive/MyDrive/test2/W*1[0-3].bmp",recursive=True)
for i in range(len(list_of_names2)):
  list_of_names.append(list_of_names2[i])
print(len(list_of_names))
for i in range(650):
  if sub1 in list_of_names[i]:
    # print ("Found!")
    list1.append(list_of_names[i])
  if sub2 in list_of_names[i]:
    # print ("Found!")
    list2.append(list_of_names[i])
  if sub3 in list_of_names[i]:
    # print ("Found!")
    list3.append(list_of_names[i])
  if sub4 in list_of_names[i]:
    # print ("Found!")
    list4.append(list_of_names[i])
  if sub5 in list_of_names[i]:
    # print ("Found!")
    list5.append(list_of_names[i])
  if sub6 in list_of_names[i]:
    # print ("Found!")
    list6.append(list_of_names[i])
  if sub7 in list_of_names[i]:
    # print ("Found!")
    list7.append(list_of_names[i])
  if sub8 in list_of_names[i]:
    # print ("Found!")
    list8.append(list_of_names[i])
  if sub9 in list_of_names[i]:
    # print ("Found!")
    list9.append(list_of_names[i])
  if sub10 in list_of_names[i]:
    # print ("Found!")
    list10.append(list_of_names[i])
  if sub11 in list_of_names[i]:
    # print ("Found!")
    list11.append(list_of_names[i])
  if sub12 in list_of_names[i]:
    # print ("Found!")
    list12.append(list_of_names[i])
  if sub13 in list_of_names[i]:
    # print ("Found!")
    list13.append(list_of_names[i])
  if sub14 in list_of_names[i]:
    # print ("Found!")
    list14.append(list_of_names[i])
  if sub15 in list_of_names[i]:
    # print ("Found!")
    list15.append(list_of_names[i])
  if sub16 in list_of_names[i]:
    # print ("Found!")
    list16.append(list_of_names[i])
  if sub17 in list_of_names[i]:
    # print ("Found!")
    list17.append(list_of_names[i])
  if sub18 in list_of_names[i]:
    # print ("Found!")
    list18.append(list_of_names[i])
  if sub19 in list_of_names[i]:
    # print ("Found!")
    list19.append(list_of_names[i])
  if sub20 in list_of_names[i]:
    # print ("Found!")
    list20.append(list_of_names[i])
  if sub21 in list_of_names[i]:
    # print ("Found!")
    list21.append(list_of_names[i])
  if sub22 in list_of_names[i]:
    # print ("Found!")
    list22.append(list_of_names[i])
  if sub23 in list_of_names[i]:
    # print ("Found!")
    list23.append(list_of_names[i])
  if sub24 in list_of_names[i]:
    # print ("Found!")
    list24.append(list_of_names[i])
  if sub25 in list_of_names[i]:
    # print ("Found!")
    list25.append(list_of_names[i])
  if sub26 in list_of_names[i]:
    # print ("Found!")
    list26.append(list_of_names[i])
  if sub27 in list_of_names[i]:
    # print ("Found!")
    list27.append(list_of_names[i])
  if sub28 in list_of_names[i]:
    # print ("Found!")
    list28.append(list_of_names[i])
  if sub29 in list_of_names[i]:
    # print ("Found!")
    list29.append(list_of_names[i])
  if sub30 in list_of_names[i]:
    # print ("Found!")
    list30.append(list_of_names[i])
  if sub31 in list_of_names[i]:
    # print ("Found!")
    list31.append(list_of_names[i])
  if sub32 in list_of_names[i]:
    # print ("Found!")
    list32.append(list_of_names[i])
  if sub33 in list_of_names[i]:
    # print ("Found!")
    list33.append(list_of_names[i])
  if sub34 in list_of_names[i]:
    # print ("Found!")
    list34.append(list_of_names[i])
  if sub35 in list_of_names[i]:
    # print ("Found!")
    list35.append(list_of_names[i])
  if sub36 in list_of_names[i]:
    # print ("Found!")
    list36.append(list_of_names[i])
  if sub37 in list_of_names[i]:
    # print ("Found!")
    list37.append(list_of_names[i])
  if sub38 in list_of_names[i]:
    # print ("Found!")
    list38.append(list_of_names[i])
  if sub39 in list_of_names[i]:
    # print ("Found!")
    list39.append(list_of_names[i])
  if sub40 in list_of_names[i]:
    # print ("Found!")
    list40.append(list_of_names[i])
  if sub41 in list_of_names[i]:
    # prnt ("Found!")
    list41.append(list_of_names[i])
  if sub42 in list_of_names[i]:
    # print ("Found!")
    list42.append(list_of_names[i])
  if sub43 in list_of_names[i]:
    # print ("Found!")
    list43.append(list_of_names[i])
  if sub44 in list_of_names[i]:
    # print ("Found!")
    list44.append(list_of_names[i])
  if sub45 in list_of_names[i]:
    # print ("Found!")
    list45.append(list_of_names[i])
  if sub46 in list_of_names[i]:
    # print ("Found!")
    list46.append(list_of_names[i])
  if sub47 in list_of_names[i]:
    # print ("Found!")
    list47.append(list_of_names[i])
  if sub48 in list_of_names[i]:
    # print ("Found!")
    list48.append(list_of_names[i])
  if sub49 in list_of_names[i]:
    # print ("Found!")
    list49.append(list_of_names[i])
  if sub50 in list_of_names[i]:
    # print ("Found!")
    list50.append(list_of_names[i])

print(len(list1))
a1=np.asarray(list1)
a2=np.asarray(list2)
a3=np.asarray(list3)
a4=np.asarray(list4)
a5=np.asarray(list5)
a6=np.asarray(list6)
a7=np.asarray(list7)
a8=np.asarray(list8)
a9=np.asarray(list9)
a10=np.asarray(list10)
a11=np.asarray(list11)
a12=np.asarray(list12)
a13=np.asarray(list13)
a14=np.asarray(list14)
a15=np.asarray(list15)
a16=np.asarray(list16)
a17=np.asarray(list17)
a18=np.asarray(list18)
a19=np.asarray(list19)
a20=np.asarray(list20)
a21=np.asarray(list21)
a22=np.asarray(list22)
a23=np.asarray(list23)
a24=np.asarray(list24)
a25=np.asarray(list25)
a26=np.asarray(list26)
a27=np.asarray(list27)
a28=np.asarray(list28)
a29=np.asarray(list29)
a30=np.asarray(list30)
a31=np.asarray(list31)
a32=np.asarray(list32)
a33=np.asarray(list33)
a34=np.asarray(list34)
a35=np.asarray(list35)
a36=np.asarray(list36)
a37=np.asarray(list37)
a38=np.asarray(list38)
a39=np.asarray(list39)
a40=np.asarray(list40)
a41=np.asarray(list41)
a42=np.asarray(list42)
a43=np.asarray(list43)
a44=np.asarray(list44)
a45=np.asarray(list45)
a46=np.asarray(list46)
a47=np.asarray(list47)
a48=np.asarray(list48)
a49=np.asarray(list49)
a50=np.asarray(list50)
a1 = np.reshape(a1,(1, a1.size))
a2 = np.reshape(a2,(1, a2.size))
a3 = np.reshape(a3,(1, a3.size))
a4 = np.reshape(a4,(1, a4.size))
a5 = np.reshape(a5,(1, a5.size))
a6 = np.reshape(a6,(1, a6.size))
a7 = np.reshape(a7,(1, a7.size))
a8 = np.reshape(a8,(1, a8.size))
a9 = np.reshape(a9,(1, a9.size))
a10 = np.reshape(a10,(1, a10.size))
a11 = np.reshape(a11,(1, a11.size))
a12 = np.reshape(a12,(1, a12.size))
a13 = np.reshape(a13,(1, a13.size))
a14 = np.reshape(a14,(1, a14.size))
a15 = np.reshape(a15,(1, a15.size))
a16 = np.reshape(a16,(1, a16.size))
a17 = np.reshape(a17,(1, a17.size))
a18 = np.reshape(a18,(1, a18.size))
a19 = np.reshape(a19,(1, a19.size))
a20 = np.reshape(a20,(1, a20.size))
a21 = np.reshape(a21,(1, a21.size))
a22 = np.reshape(a22,(1, a22.size))
a23 = np.reshape(a23,(1, a23.size))
a24 = np.reshape(a24,(1, a24.size))
a25 = np.reshape(a25,(1, a25.size))
a26 = np.reshape(a26,(1, a26.size))
a27 = np.reshape(a27,(1, a27.size))
a28 = np.reshape(a28,(1, a28.size))
a29 = np.reshape(a29,(1, a29.size))
a30 = np.reshape(a30,(1, a30.size))
a31 = np.reshape(a31,(1, a31.size))
a32 = np.reshape(a32,(1, a32.size))
a33 = np.reshape(a33,(1, a33.size))
a34 = np.reshape(a34,(1, a34.size))
a35 = np.reshape(a35,(1, a35.size))
a36 = np.reshape(a36,(1, a36.size))
a37 = np.reshape(a37,(1, a37.size))
a38 = np.reshape(a38,(1, a38.size))
a39 = np.reshape(a39,(1, a39.size))
a40 = np.reshape(a40,(1, a40.size))
a41 = np.reshape(a41,(1, a41.size))
a42 = np.reshape(a42,(1, a42.size))
a43 = np.reshape(a43,(1, a43.size))
a44 = np.reshape(a44,(1, a44.size))
a45 = np.reshape(a45,(1, a45.size))
a46 = np.reshape(a46,(1, a46.size))
a47 = np.reshape(a47,(1, a47.size))
a48 = np.reshape(a48,(1, a48.size))
a49 = np.reshape(a49,(1, a49.size))
a50 = np.reshape(a50,(1, a50.size))
print(a50.shape)
array2=np.concatenate((a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50))
print(array2.shape)

"""**test_set**"""

import glob
# for i in range(1,51):
# fullstring = ""
sub1 = "001"
sub2 = "002"
sub3 = "003"
sub4 = "004"
sub5 = "005"
sub6 = "006"
sub7 = "007"
sub8 = "008"
sub9 = "009"
sub10 = "010"
sub11 = "011"
sub12 = "012"
sub13 = "013"
sub14 = "014"
sub15 = "015"
sub16 = "016"
sub17 = "017"
sub18 = "018"
sub19 = "019"
sub20 = "020"
sub21 = "021"
sub22 = "022"
sub23 = "023"
sub24 = "024"
sub25 = "025"
sub26 = "026"
sub27 = "027"
sub28 = "028"
sub29 = "029"
sub30 = "030"
sub31 = "031"
sub32 = "032"
sub33 = "033"
sub34 = "034"
sub35 = "035"
sub36 = "036"
sub37 = "037"
sub38 = "038"
sub39 = "039"
sub40 = "040"
sub41 = "041"
sub42 = "042"
sub43 = "043"
sub44 = "044"
sub45 = "045"
sub46 = "046"
sub47 = "047"
sub48 = "048"
sub49 = "049"
sub50 = "050"
# sub15 = "050"
list1=[]
list2=[]
list3=[]
list4=[]
list5=[]
list6=[]
list7=[]
list8=[]
list9=[]
list10=[]
list11=[]
list11=[]
list12=[]
list13=[]
list14=[]
list15=[]
list16=[]
list17=[]
list18=[]
list19=[]
list20=[]
list21=[]
list22=[]
list23=[]
list24=[]
list25=[]
list26=[]
list27=[]
list28=[]
list29=[]
list30=[]
list31=[]
list32=[]
list33=[]
list34=[]
list35=[]
list36=[]
list37=[]
list38=[]
list39=[]
list40=[]
list41=[]
list42=[]
list43=[]
list44=[]
list45=[]
list46=[]
list47=[]
list48=[]
list49=[]
list50=[]
list_of_names=glob.glob("/content/drive/MyDrive/test2/M*1[4-9].bmp",recursive=True)
list_of_names2=glob.glob("/content/drive/MyDrive/test2/M*2[0-6].bmp",recursive=True)
for i in range(len(list_of_names2)):
  list_of_names.append(list_of_names2[i])
print(len(list_of_names))
# list_of_names.append(temp)
# print(list_of_names)
# print(len(list_of_names))
for i in range(650):
  if sub1 in list_of_names[i]:
    # print ("Found!")
    list1.append(list_of_names[i])
  if sub2 in list_of_names[i]:
    # print ("Found!")
    list2.append(list_of_names[i])
  if sub3 in list_of_names[i]:
    # print ("Found!")
    list3.append(list_of_names[i])
  if sub4 in list_of_names[i]:
    # print ("Found!")
    list4.append(list_of_names[i])
  if sub5 in list_of_names[i]:
    # print ("Found!")
    list5.append(list_of_names[i])
  if sub6 in list_of_names[i]:
    # print ("Found!")
    list6.append(list_of_names[i])
  if sub7 in list_of_names[i]:
    # print ("Found!")
    list7.append(list_of_names[i])
  if sub8 in list_of_names[i]:
    # print ("Found!")
    list8.append(list_of_names[i])
  if sub9 in list_of_names[i]:
    # print ("Found!")
    list9.append(list_of_names[i])
  if sub10 in list_of_names[i]:
    # print ("Found!")
    list10.append(list_of_names[i])
  if sub11 in list_of_names[i]:
    # print ("Found!")
    list11.append(list_of_names[i])
  if sub12 in list_of_names[i]:
    # print ("Found!")
    list12.append(list_of_names[i])
  if sub13 in list_of_names[i]:
    # print ("Found!")
    list13.append(list_of_names[i])
  if sub14 in list_of_names[i]:
    # print ("Found!")
    list14.append(list_of_names[i])
  if sub15 in list_of_names[i]:
    # print ("Found!")
    list15.append(list_of_names[i])
  if sub16 in list_of_names[i]:
    # print ("Found!")
    list16.append(list_of_names[i])
  if sub17 in list_of_names[i]:
    # print ("Found!")
    list17.append(list_of_names[i])
  if sub18 in list_of_names[i]:
    # print ("Found!")
    list18.append(list_of_names[i])
  if sub19 in list_of_names[i]:
    # print ("Found!")
    list19.append(list_of_names[i])
  if sub20 in list_of_names[i]:
    # print ("Found!")
    list20.append(list_of_names[i])
  if sub21 in list_of_names[i]:
    # print ("Found!")
    list21.append(list_of_names[i])
  if sub22 in list_of_names[i]:
    # print ("Found!")
    list22.append(list_of_names[i])
  if sub23 in list_of_names[i]:
    # print ("Found!")
    list23.append(list_of_names[i])
  if sub24 in list_of_names[i]:
    # print ("Found!")
    list24.append(list_of_names[i])
  if sub25 in list_of_names[i]:
    # print ("Found!")
    list25.append(list_of_names[i])
  if sub26 in list_of_names[i]:
    # print ("Found!")
    list26.append(list_of_names[i])
  if sub27 in list_of_names[i]:
    # print ("Found!")
    list27.append(list_of_names[i])
  if sub28 in list_of_names[i]:
    # print ("Found!")
    list28.append(list_of_names[i])
  if sub29 in list_of_names[i]:
    # print ("Found!")
    list29.append(list_of_names[i])
  if sub30 in list_of_names[i]:
    # print ("Found!")
    list30.append(list_of_names[i])
  if sub31 in list_of_names[i]:
    # print ("Found!")
    list31.append(list_of_names[i])
  if sub32 in list_of_names[i]:
    # print ("Found!")
    list32.append(list_of_names[i])
  if sub33 in list_of_names[i]:
    # print ("Found!")
    list33.append(list_of_names[i])
  if sub34 in list_of_names[i]:
    # print ("Found!")
    list34.append(list_of_names[i])
  if sub35 in list_of_names[i]:
    # print ("Found!")
    list35.append(list_of_names[i])
  if sub36 in list_of_names[i]:
    # print ("Found!")
    list36.append(list_of_names[i])
  if sub37 in list_of_names[i]:
    # print ("Found!")
    list37.append(list_of_names[i])
  if sub38 in list_of_names[i]:
    # print ("Found!")
    list38.append(list_of_names[i])
  if sub39 in list_of_names[i]:
    # print ("Found!")
    list39.append(list_of_names[i])
  if sub40 in list_of_names[i]:
    # print ("Found!")
    list40.append(list_of_names[i])
  if sub41 in list_of_names[i]:
    # prnt ("Found!")
    list41.append(list_of_names[i])
  if sub42 in list_of_names[i]:
    # print ("Found!")
    list42.append(list_of_names[i])
  if sub43 in list_of_names[i]:
    # print ("Found!")
    list43.append(list_of_names[i])
  if sub44 in list_of_names[i]:
    # print ("Found!")
    list44.append(list_of_names[i])
  if sub45 in list_of_names[i]:
    # print ("Found!")
    list45.append(list_of_names[i])
  if sub46 in list_of_names[i]:
    # print ("Found!")
    list46.append(list_of_names[i])
  if sub47 in list_of_names[i]:
    # print ("Found!")
    list47.append(list_of_names[i])
  if sub48 in list_of_names[i]:
    # print ("Found!")
    list48.append(list_of_names[i])
  if sub49 in list_of_names[i]:
    # print ("Found!")
    list49.append(list_of_names[i])
  if sub50 in list_of_names[i]:
    # print ("Found!")
    list50.append(list_of_names[i])

print(len(list1))
a1=np.asarray(list1)
a2=np.asarray(list2)
a3=np.asarray(list3)
a4=np.asarray(list4)
a5=np.asarray(list5)
a6=np.asarray(list6)
a7=np.asarray(list7)
a8=np.asarray(list8)
a9=np.asarray(list9)
a10=np.asarray(list10)
a11=np.asarray(list11)
a12=np.asarray(list12)
a13=np.asarray(list13)
a14=np.asarray(list14)
a15=np.asarray(list15)
a16=np.asarray(list16)
a17=np.asarray(list17)
a18=np.asarray(list18)
a19=np.asarray(list19)
a20=np.asarray(list20)
a21=np.asarray(list21)
a22=np.asarray(list22)
a23=np.asarray(list23)
a24=np.asarray(list24)
a25=np.asarray(list25)
a26=np.asarray(list26)
a27=np.asarray(list27)
a28=np.asarray(list28)
a29=np.asarray(list29)
a30=np.asarray(list30)
a31=np.asarray(list31)
a32=np.asarray(list32)
a33=np.asarray(list33)
a34=np.asarray(list34)
a35=np.asarray(list35)
a36=np.asarray(list36)
a37=np.asarray(list37)
a38=np.asarray(list38)
a39=np.asarray(list39)
a40=np.asarray(list40)
a41=np.asarray(list41)
a42=np.asarray(list42)
a43=np.asarray(list43)
a44=np.asarray(list44)
a45=np.asarray(list45)
a46=np.asarray(list46)
a47=np.asarray(list47)
a48=np.asarray(list48)
a49=np.asarray(list49)
a50=np.asarray(list50)
a1 = np.reshape(a1,(1, a1.size))
a2 = np.reshape(a2,(1, a2.size))
a3 = np.reshape(a3,(1, a3.size))
a4 = np.reshape(a4,(1, a4.size))
a5 = np.reshape(a5,(1, a5.size))
a6 = np.reshape(a6,(1, a6.size))
a7 = np.reshape(a7,(1, a7.size))
a8 = np.reshape(a8,(1, a8.size))
a9 = np.reshape(a9,(1, a9.size))
a10 = np.reshape(a10,(1, a10.size))
a11 = np.reshape(a11,(1, a11.size))
a12 = np.reshape(a12,(1, a12.size))
a13 = np.reshape(a13,(1, a13.size))
a14 = np.reshape(a14,(1, a14.size))
a15 = np.reshape(a15,(1, a15.size))
a16 = np.reshape(a16,(1, a16.size))
a17 = np.reshape(a17,(1, a17.size))
a18 = np.reshape(a18,(1, a18.size))
a19 = np.reshape(a19,(1, a19.size))
a20 = np.reshape(a20,(1, a20.size))
a21 = np.reshape(a21,(1, a21.size))
a22 = np.reshape(a22,(1, a22.size))
a23 = np.reshape(a23,(1, a23.size))
a24 = np.reshape(a24,(1, a24.size))
a25 = np.reshape(a25,(1, a25.size))
a26 = np.reshape(a26,(1, a26.size))
a27 = np.reshape(a27,(1, a27.size))
a28 = np.reshape(a28,(1, a28.size))
a29 = np.reshape(a29,(1, a29.size))
a30 = np.reshape(a30,(1, a30.size))
a31 = np.reshape(a31,(1, a31.size))
a32 = np.reshape(a32,(1, a32.size))
a33 = np.reshape(a33,(1, a33.size))
a34 = np.reshape(a34,(1, a34.size))
a35 = np.reshape(a35,(1, a35.size))
a36 = np.reshape(a36,(1, a36.size))
a37 = np.reshape(a37,(1, a37.size))
a38 = np.reshape(a38,(1, a38.size))
a39 = np.reshape(a39,(1, a39.size))
a40 = np.reshape(a40,(1, a40.size))
a41 = np.reshape(a41,(1, a41.size))
a42 = np.reshape(a42,(1, a42.size))
a43 = np.reshape(a43,(1, a43.size))
a44 = np.reshape(a44,(1, a44.size))
a45 = np.reshape(a45,(1, a45.size))
a46 = np.reshape(a46,(1, a46.size))
a47 = np.reshape(a47,(1, a47.size))
a48 = np.reshape(a48,(1, a48.size))
a49 = np.reshape(a49,(1, a49.size))
a50 = np.reshape(a50,(1, a50.size))
print(a50.shape)
test_array1=np.concatenate((a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50))
print(test_array1.shape)

import glob
# for i in range(1,51):
# fullstring = ""
sub1 = "001"
sub2 = "002"
sub3 = "003"
sub4 = "004"
sub5 = "005"
sub6 = "006"
sub7 = "007"
sub8 = "008"
sub9 = "009"
sub10 = "010"
sub11 = "011"
sub12 = "012"
sub13 = "013"
sub14 = "014"
sub15 = "015"
sub16 = "016"
sub17 = "017"
sub18 = "018"
sub19 = "019"
sub20 = "020"
sub21 = "021"
sub22 = "022"
sub23 = "023"
sub24 = "024"
sub25 = "025"
sub26 = "026"
sub27 = "027"
sub28 = "028"
sub29 = "029"
sub30 = "030"
sub31 = "031"
sub32 = "032"
sub33 = "033"
sub34 = "034"
sub35 = "035"
sub36 = "036"
sub37 = "037"
sub38 = "038"
sub39 = "039"
sub40 = "040"
sub41 = "041"
sub42 = "042"
sub43 = "043"
sub44 = "044"
sub45 = "045"
sub46 = "046"
sub47 = "047"
sub48 = "048"
sub49 = "049"
sub50 = "050"
# sub15 = "050"
list1=[]
list2=[]
list3=[]
list4=[]
list5=[]
list6=[]
list7=[]
list8=[]
list9=[]
list10=[]
list11=[]
list11=[]
list12=[]
list13=[]
list14=[]
list15=[]
list16=[]
list17=[]
list18=[]
list19=[]
list20=[]
list21=[]
list22=[]
list23=[]
list24=[]
list25=[]
list26=[]
list27=[]
list28=[]
list29=[]
list30=[]
list31=[]
list32=[]
list33=[]
list34=[]
list35=[]
list36=[]
list37=[]
list38=[]
list39=[]
list40=[]
list41=[]
list42=[]
list43=[]
list44=[]
list45=[]
list46=[]
list47=[]
list48=[]
list49=[]
list50=[]
list_of_names=glob.glob("/content/drive/MyDrive/test2/W*1[4-9].bmp",recursive=True)
list_of_names2=glob.glob("/content/drive/MyDrive/test2/W*2[0-6].bmp",recursive=True)
for i in range(len(list_of_names2)):
  list_of_names.append(list_of_names2[i])
print(len(list_of_names))
# list_of_names.append(temp)
for i in range(650):
  if sub1 in list_of_names[i]:
    # print ("Found!")
    list1.append(list_of_names[i])
  if sub2 in list_of_names[i]:
    # print ("Found!")
    list2.append(list_of_names[i])
  if sub3 in list_of_names[i]:
    # print ("Found!")
    list3.append(list_of_names[i])
  if sub4 in list_of_names[i]:
    # print ("Found!")
    list4.append(list_of_names[i])
  if sub5 in list_of_names[i]:
    # print ("Found!")
    list5.append(list_of_names[i])
  if sub6 in list_of_names[i]:
    # print ("Found!")
    list6.append(list_of_names[i])
  if sub7 in list_of_names[i]:
    # print ("Found!")
    list7.append(list_of_names[i])
  if sub8 in list_of_names[i]:
    # print ("Found!")
    list8.append(list_of_names[i])
  if sub9 in list_of_names[i]:
    # print ("Found!")
    list9.append(list_of_names[i])
  if sub10 in list_of_names[i]:
    # print ("Found!")
    list10.append(list_of_names[i])
  if sub11 in list_of_names[i]:
    # print ("Found!")
    list11.append(list_of_names[i])
  if sub12 in list_of_names[i]:
    # print ("Found!")
    list12.append(list_of_names[i])
  if sub13 in list_of_names[i]:
    # print ("Found!")
    list13.append(list_of_names[i])
  if sub14 in list_of_names[i]:
    # print ("Found!")
    list14.append(list_of_names[i])
  if sub15 in list_of_names[i]:
    # print ("Found!")
    list15.append(list_of_names[i])
  if sub16 in list_of_names[i]:
    # print ("Found!")
    list16.append(list_of_names[i])
  if sub17 in list_of_names[i]:
    # print ("Found!")
    list17.append(list_of_names[i])
  if sub18 in list_of_names[i]:
    # print ("Found!")
    list18.append(list_of_names[i])
  if sub19 in list_of_names[i]:
    # print ("Found!")
    list19.append(list_of_names[i])
  if sub20 in list_of_names[i]:
    # print ("Found!")
    list20.append(list_of_names[i])
  if sub21 in list_of_names[i]:
    # print ("Found!")
    list21.append(list_of_names[i])
  if sub22 in list_of_names[i]:
    # print ("Found!")
    list22.append(list_of_names[i])
  if sub23 in list_of_names[i]:
    # print ("Found!")
    list23.append(list_of_names[i])
  if sub24 in list_of_names[i]:
    # print ("Found!")
    list24.append(list_of_names[i])
  if sub25 in list_of_names[i]:
    # print ("Found!")
    list25.append(list_of_names[i])
  if sub26 in list_of_names[i]:
    # print ("Found!")
    list26.append(list_of_names[i])
  if sub27 in list_of_names[i]:
    # print ("Found!")
    list27.append(list_of_names[i])
  if sub28 in list_of_names[i]:
    # print ("Found!")
    list28.append(list_of_names[i])
  if sub29 in list_of_names[i]:
    # print ("Found!")
    list29.append(list_of_names[i])
  if sub30 in list_of_names[i]:
    # print ("Found!")
    list30.append(list_of_names[i])
  if sub31 in list_of_names[i]:
    # print ("Found!")
    list31.append(list_of_names[i])
  if sub32 in list_of_names[i]:
    # print ("Found!")
    list32.append(list_of_names[i])
  if sub33 in list_of_names[i]:
    # print ("Found!")
    list33.append(list_of_names[i])
  if sub34 in list_of_names[i]:
    # print ("Found!")
    list34.append(list_of_names[i])
  if sub35 in list_of_names[i]:
    # print ("Found!")
    list35.append(list_of_names[i])
  if sub36 in list_of_names[i]:
    # print ("Found!")
    list36.append(list_of_names[i])
  if sub37 in list_of_names[i]:
    # print ("Found!")
    list37.append(list_of_names[i])
  if sub38 in list_of_names[i]:
    # print ("Found!")
    list38.append(list_of_names[i])
  if sub39 in list_of_names[i]:
    # print ("Found!")
    list39.append(list_of_names[i])
  if sub40 in list_of_names[i]:
    # print ("Found!")
    list40.append(list_of_names[i])
  if sub41 in list_of_names[i]:
    # prnt ("Found!")
    list41.append(list_of_names[i])
  if sub42 in list_of_names[i]:
    # print ("Found!")
    list42.append(list_of_names[i])
  if sub43 in list_of_names[i]:
    # print ("Found!")
    list43.append(list_of_names[i])
  if sub44 in list_of_names[i]:
    # print ("Found!")
    list44.append(list_of_names[i])
  if sub45 in list_of_names[i]:
    # print ("Found!")
    list45.append(list_of_names[i])
  if sub46 in list_of_names[i]:
    # print ("Found!")
    list46.append(list_of_names[i])
  if sub47 in list_of_names[i]:
    # print ("Found!")
    list47.append(list_of_names[i])
  if sub48 in list_of_names[i]:
    # print ("Found!")
    list48.append(list_of_names[i])
  if sub49 in list_of_names[i]:
    # print ("Found!")
    list49.append(list_of_names[i])
  if sub50 in list_of_names[i]:
    # print ("Found!")
    list50.append(list_of_names[i])

print(len(list1))
a1=np.asarray(list1)
a2=np.asarray(list2)
a3=np.asarray(list3)
a4=np.asarray(list4)
a5=np.asarray(list5)
a6=np.asarray(list6)
a7=np.asarray(list7)
a8=np.asarray(list8)
a9=np.asarray(list9)
a10=np.asarray(list10)
a11=np.asarray(list11)
a12=np.asarray(list12)
a13=np.asarray(list13)
a14=np.asarray(list14)
a15=np.asarray(list15)
a16=np.asarray(list16)
a17=np.asarray(list17)
a18=np.asarray(list18)
a19=np.asarray(list19)
a20=np.asarray(list20)
a21=np.asarray(list21)
a22=np.asarray(list22)
a23=np.asarray(list23)
a24=np.asarray(list24)
a25=np.asarray(list25)
a26=np.asarray(list26)
a27=np.asarray(list27)
a28=np.asarray(list28)
a29=np.asarray(list29)
a30=np.asarray(list30)
a31=np.asarray(list31)
a32=np.asarray(list32)
a33=np.asarray(list33)
a34=np.asarray(list34)
a35=np.asarray(list35)
a36=np.asarray(list36)
a37=np.asarray(list37)
a38=np.asarray(list38)
a39=np.asarray(list39)
a40=np.asarray(list40)
a41=np.asarray(list41)
a42=np.asarray(list42)
a43=np.asarray(list43)
a44=np.asarray(list44)
a45=np.asarray(list45)
a46=np.asarray(list46)
a47=np.asarray(list47)
a48=np.asarray(list48)
a49=np.asarray(list49)
a50=np.asarray(list50)
a1 = np.reshape(a1,(1, a1.size))
a2 = np.reshape(a2,(1, a2.size))
a3 = np.reshape(a3,(1, a3.size))
a4 = np.reshape(a4,(1, a4.size))
a5 = np.reshape(a5,(1, a5.size))
a6 = np.reshape(a6,(1, a6.size))
a7 = np.reshape(a7,(1, a7.size))
a8 = np.reshape(a8,(1, a8.size))
a9 = np.reshape(a9,(1, a9.size))
a10 = np.reshape(a10,(1, a10.size))
a11 = np.reshape(a11,(1, a11.size))
a12 = np.reshape(a12,(1, a12.size))
a13 = np.reshape(a13,(1, a13.size))
a14 = np.reshape(a14,(1, a14.size))
a15 = np.reshape(a15,(1, a15.size))
a16 = np.reshape(a16,(1, a16.size))
a17 = np.reshape(a17,(1, a17.size))
a18 = np.reshape(a18,(1, a18.size))
a19 = np.reshape(a19,(1, a19.size))
a20 = np.reshape(a20,(1, a20.size))
a21 = np.reshape(a21,(1, a21.size))
a22 = np.reshape(a22,(1, a22.size))
a23 = np.reshape(a23,(1, a23.size))
a24 = np.reshape(a24,(1, a24.size))
a25 = np.reshape(a25,(1, a25.size))
a26 = np.reshape(a26,(1, a26.size))
a27 = np.reshape(a27,(1, a27.size))
a28 = np.reshape(a28,(1, a28.size))
a29 = np.reshape(a29,(1, a29.size))
a30 = np.reshape(a30,(1, a30.size))
a31 = np.reshape(a31,(1, a31.size))
a32 = np.reshape(a32,(1, a32.size))
a33 = np.reshape(a33,(1, a33.size))
a34 = np.reshape(a34,(1, a34.size))
a35 = np.reshape(a35,(1, a35.size))
a36 = np.reshape(a36,(1, a36.size))
a37 = np.reshape(a37,(1, a37.size))
a38 = np.reshape(a38,(1, a38.size))
a39 = np.reshape(a39,(1, a39.size))
a40 = np.reshape(a40,(1, a40.size))
a41 = np.reshape(a41,(1, a41.size))
a42 = np.reshape(a42,(1, a42.size))
a43 = np.reshape(a43,(1, a43.size))
a44 = np.reshape(a44,(1, a44.size))
a45 = np.reshape(a45,(1, a45.size))
a46 = np.reshape(a46,(1, a46.size))
a47 = np.reshape(a47,(1, a47.size))
a48 = np.reshape(a48,(1, a48.size))
a49 = np.reshape(a49,(1, a49.size))
a50 = np.reshape(a50,(1, a50.size))
print(a50.shape)
test_array2=np.concatenate((a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50))
print(test_array2.shape)

array_of_images=np.concatenate((array1, array2))
print(array_of_images.shape)

testarray_of_images=np.concatenate((test_array1, test_array2))
print(testarray_of_images.shape)

import os
import cv2 as cv
import matplotlib.pyplot as plt
import glob
import numpy as np

rows = cols = 0
X = D = None
n = 0
train_img = []
H_filter=np.empty((100,165,120))


for counter in range(100):
  X = D = None
  n = 0
  rows = cols = 0
  for image in array_of_images[counter,:]:
      img= cv.imread(image,0)
      plt.imshow(img,cmap='gray')
      # plt.show()
      # train_img.append(n)
      # img = cv.resize(img, (125, 125), interpolation=cv.INTER_AREA)

      # apply dft and shift the dc component from top left to the centre
      dft = np.fft.fft2(img)
      # dft = np.fft.fftshift(dft)

      # dft = 20*np.log(cv2.magnitude(dft[:,:,0],dft[:,:,1]))
      if X is None:
          rows, cols = img.shape
          X = dft.flatten()
      else:
          X = np.c_[X, dft.flatten()]
      n = n + 1

  print(X.shape)
  d = rows * cols
  Dinv = np.zeros((d,1))

  for i in range(d):
      a = 0
      for j in range(n):
          a = a +  np.absolute(X[i,j])*np.absolute(X[i,j])
      Dinv[i] = 1/(a/n)
  ###################### find Dinv * X

  dim = (d,n)


  mul = X
  for i in range(d):     #for i in range(d):  if x1[d]!=0 H[1
      mul[i,:]= mul[i,:]*Dinv[i]
  ###################### find  conjugate of X

  Xcon = np.transpose(np.conjugate(X))

  ##################### now the H filter
  print ("Xshape",X.shape," ",Xcon.shape," ",mul.shape)

  u = np.ones((n,1))
  H = np.dot (  np.dot(mul, np.linalg.inv(np.dot(Xcon, mul)) ),  u)
  #H = (mul *  np.linalg.inv(Xcon*mul) )* u

  H = np.reshape(H, (rows, cols))
  print("H.shape",H.shape)
  H_filter[counter,:,:]=H

print(H_filter.shape)

for i in range(100):
  fig = plt.figure(figsize=(40,40))
  plt.imshow(np.log(abs(H_filter[i,:,:])),cmap='gray')
  plt.title("Filter "+str(i+1))
  plt.savefig("/content/drive/MyDrive/H_filter_c/%d.jpg"%(i+1))
  plt.close(fig)

recognition=np.zeros((100,13))
recognition_result=np.empty((100,13), dtype='object')
# strArr = numpy.empty(10, dtype='string')
for i in range(100):
  # fig = plt.figure(figsize=(40,40))
  for j in range(13):
    image= cv.imread(testarray_of_images[i,j],0)
    f1 = np.fft.fft2(image)

# The default result center point position is in the upper left corner,
# Call fftshift() function to shift to the middle position
    fshift1 = np.fft.fftshift(f1)
    Hcon = np.conjugate(H_filter[i,:,:])
    F_dim = f1 * Hcon

    # Do the inverse Fourier transform to get back to an image.
    # Since we started with a real image, we only look at the real part of
    # the output.
    out=np.fft.ifft2(F_dim)
    out=np.fft.ifftshift(out)
    image_filtered = np.real(out)
    maximum=np.max(image_filtered[(image.shape[0]//2)-20 : (image.shape[0]//2)+20, (image.shape[1]//2)-20 : (image.shape[1]//2)+20].ravel())
    peak=np.where(image_filtered==maximum)
    miu=np.mean(image_filtered[peak[0][0]-20 : peak[0][0]+20 , peak[1][0]-20 : peak[1][0]+20])
    sigma=np.std(image_filtered[peak[0][0]-20 : peak[0][0]+20 , peak[1][0]-20 : peak[1][0]+20])
    if (maximum-miu)/sigma >8:
      recognition[i,j]=1
      recognition_result[i,j]="yes"
    else:
      recognition_result[i,j]="no"

  #   plt.subplot(5,3,j+1)
  #   for k in range(image_filtered.shape[1]):
  #     plt.plot(image_filtered[:,k])
  #   plt.title("test_image "+str(j))
  # plt.savefig("/content/drive/MyDrive/part_C_4/%d.jpg"%(i+1))
  #   # plt.show()
  # plt.close(fig)

recognition_rate=np.sum(recognition)/1300
print(recognition_rate)
print(recognition_result)

# def print_results_table(data, teams_list):
#     str_l = max(len(t) for t in teams_list)
#     print(" ".join(['{:>{length}s}'.format(t, length = str_l) for t in [" "] + teams_list]))
#     for t, row in zip(teams_list, data):
#         print(" ".join(['{:>{length}s}'.format(str(x), length = str_l) for x in [t] + row]))

recog_list=recognition_result.tolist()
# teams_list = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13"]
# data = recognition_result
# print_results_table(recog_list, teams_list)

from tabulate import tabulate

# l = [["Hassan", 21, "LUMS"], ["Ali", 22, "FAST"], ["Ahmed", 23, "UET"]]
table = tabulate(recog_list, headers=["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13"], tablefmt='orgtbl')

print(table)

d = rows * cols
Dinv = np.zeros((d,1))

for i in range(d):
    a = 0
    for j in range(n):
        a = a +  np.absolute(X[i,j])*np.absolute(X[i,j])
    Dinv[i] = 1/(a/n)
###################### find Dinv * X

dim = (d,n)


mul = X
for i in range(d):     #for i in range(d):  if x1[d]!=0 H[1
    mul[i,:]= mul[i,:]*Dinv[i]
###################### find  conjugate of X

Xcon = np.transpose(np.conjugate(X))

##################### now the H filter
print ("Xshape",X.shape," ",Xcon.shape," ",mul.shape)

u = np.ones((n,1))
H = np.dot (  np.dot(mul, np.linalg.inv(np.dot(Xcon, mul)) ),  u)
#H = (mul *  np.linalg.inv(Xcon*mul) )* u

H = np.reshape(H, (rows, cols))

print(H.shape)

filter_H = np.log(np.abs(H))

# Show results
plt.figure(figsize=(6.4*5,4.8*5),constrained_layout=False)
plt.subplot(131), plt.imshow(filter_H, 'gray'), plt.title('Original image')
plt.axis('off')
# plt.subplot(132), plt.imshow(fimg1, 'gray'), plt.title('Image spectrum')
# plt.axis('off')
plt.show()

image= cv.imread('/content/drive/MyDrive/test2/M-004-13.bmp',0)
print(image.shape)
plt.imshow(image,cmap='gray')
plt.show()

import numpy as np
# image = cv.resize(image, (125, 125), interpolation=cv.INTER_AREA)
f1 = np.fft.fft2(image)

# The default result center point position is in the upper left corner,
# Call fftshift() function to shift to the middle position
fshift1 = np.fft.fftshift(f1)

# fft result is a complex number, its absolute value result is amplitude
fimg1 = np.log(np.abs(fshift1))

plt.figure(figsize=(6.4*5,4.8*5),constrained_layout=False)
plt.subplot(131), plt.imshow(image, 'gray'), plt.title('Original image')
plt.axis('off')
plt.subplot(132), plt.imshow(fimg1, 'gray'), plt.title('Image spectrum')
plt.axis('off')

Hcon = np.conjugate(H)
F_dim = f1 * Hcon

# Do the inverse Fourier transform to get back to an image.
# Since we started with a real image, we only look at the real part of
# the output.
out=np.fft.ifft2(F_dim)
out=np.fft.ifftshift(out)
image_filtered = np.real(out)

f_, (ax0, ax1) = plt.subplots(2, 1, figsize=(4.8, 7))
ax0.imshow(np.log10(1 + np.abs(H)), cmap='gray')
ax0.set_title('filter')

ax1.imshow(np.log10(1+np.abs(F_dim)), cmap='gray')
ax1.set_title('spectrom after product')
plt.show()

for i in range(image_filtered.shape[1]):
  plt.plot(image_filtered[:,i])
plt.show()
# ax2.imshow(image_filtered, cmap='gray')
# ax2.set_title('after IFT ')
# plt.show()